#!/usr/bin/env python3
"""Merge chunk-*.json + corroboration.json into data/data.js (window globals)."""
import json, glob, os, sys, re

HERE = os.path.dirname(os.path.abspath(__file__))

CATEGORIES = [
    ("american-dynamism", "American Dynamism", "美國動能"),
    ("apps",              "Apps",              "應用程式"),
    ("bio-health",        "Bio + Health",      "生技與健康"),
    ("consumer",          "Consumer Tech",     "消費科技"),
    ("crypto",            "Crypto",            "加密貨幣"),
    ("enterprise-fintech","Enterprise + Fintech","企業與金融科技"),
    ("games",             "Games",             "遊戲"),
    ("growth",            "Growth",            "成長期科技"),
    ("infrastructure",    "Infrastructure",    "基礎設施"),
    ("speedrun",          "Speedrun",          "Speedrun 加速器"),
]

# 1) load chunks
items = []
for fp in sorted(glob.glob(os.path.join(HERE, "chunk-*.json"))):
    with open(fp, encoding="utf-8") as f:
        arr = json.load(f)
    print(f"  {os.path.basename(fp)}: {len(arr)}")
    items.extend(arr)

# 2) dedupe / validate slugs
seen = {}
for it in items:
    s = it["slug"]
    if s in seen:
        # make unique
        n = 2
        while f"{s}-{n}" in seen:
            n += 1
        it["slug"] = f"{s}-{n}"
    seen[it["slug"]] = it

# 3) attach corroboration by best slug match
corr_fp = os.path.join(HERE, "corroboration.json")
attached = 0
if os.path.exists(corr_fp):
    with open(corr_fp, encoding="utf-8") as f:
        corr = json.load(f)

    def tokens(s):
        return set(re.sub(r"[^a-z0-9 ]", " ", s.lower().replace("-", " ")).split())

    for key, payload in corr.items():
        # exact match first
        target = seen.get(key)
        if target is None:
            ktok = tokens(key)
            best, score = None, 0
            for it in items:
                ov = len(ktok & tokens(it["slug"]))
                if ov > score:
                    best, score = it, ov
            if score >= 3:
                target = best
        if target is not None:
            target["update"] = payload.get("update")
            target["links"] = payload.get("links")
            attached += 1
        else:
            print(f"  ! corroboration unmatched: {key}", file=sys.stderr)

# 4) stats
by_year, by_cat = {}, {}
for it in items:
    by_year[it["year"]] = by_year.get(it["year"], 0) + 1
    by_cat[it["category"]] = by_cat.get(it["category"], 0) + 1
print(f"TOTAL {len(items)} | years {by_year} | corroboration attached {attached}")
unknown = sorted(set(by_cat) - {c[0] for c in CATEGORIES})
if unknown:
    print(f"  ! unknown categories: {unknown}", file=sys.stderr)
print("  per-category:", by_cat)

# 5) sort: 2026 first, then by category order, then title
catorder = {c[0]: i for i, c in enumerate(CATEGORIES)}
items.sort(key=lambda it: (it["year"] != "2026", catorder.get(it["category"], 99),
                           (it["title"]["en"] or "").lower()))

categories = [{"key": k, "en": en, "zh": zh} for (k, en, zh) in CATEGORIES
              if k in by_cat]
years = sorted(by_year, reverse=True)
meta = {
    "title": {"en": "a16z Big Ideas Explorer", "zh": "a16z 科技大點子圖鑑"},
    "subtitle": {"en": "96 predictions from Andreessen Horowitz · 2025 & 2026",
                 "zh": "Andreessen Horowitz 的 96 個科技預測 · 2025 與 2026"},
}

def dump(obj):
    return json.dumps(obj, ensure_ascii=False, indent=2)

out = os.path.join(HERE, "data.js")
with open(out, "w", encoding="utf-8") as f:
    f.write("/* Auto-generated by _assemble.py — a16z Big Ideas dataset */\n")
    f.write("window.SITE_META = " + dump(meta) + ";\n\n")
    f.write("window.SITE_YEARS = " + dump(years) + ";\n\n")
    f.write("window.SITE_CATEGORIES = " + dump(categories) + ";\n\n")
    f.write("window.SITE_DATA = " + dump(items) + ";\n")
print(f"WROTE {out} ({os.path.getsize(out)} bytes)")
